"""
critique.py
-----------
Self-Critique Agent powered by Google Gemini and LangChain.

This agent reviews the initial clinical reasoning output and checks for:
  - Evidence support (is reasoning grounded in provided data?)
  - Missing information flags
  - Potential hallucinations (claims not supported by data)
  - Contradictions (internal inconsistencies)
  - Guideline mismatch
  - Suggests a revised / refined reasoning
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv

from memory_agent import memory_agent

# LangChain Imports
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_classic.prompts import PromptTemplate
from langchain_classic.chains import LLMChain

load_dotenv(Path(__file__).parent.parent / ".env")

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    api_key=os.getenv("GEMINI_API_KEY", ""),
    temperature=0.1
)

def run_critique_agent(
    patient: dict,
    visit: dict,
    reasoning: str,
    case_summary: str,
    guidelines_used: list[str],
) -> dict:
    vitals = visit.get("vitals", {})
    labs = visit.get("labs", {})

    # Retrieve Episodic Memory for historical consistency check
    episodes = memory_agent.retrieve_episodes(
        current_visit=visit,
        patient_id=patient["patient_id"],
        top_k=3,
    )
    episodic_summary = memory_agent.summarize_episodes(episodes)

    prompt_template = PromptTemplate(
        input_variables=["patient_info", "current_visit", "vitals", "labs", "case_summary", "reasoning", "guidelines", "episodic_summary"],
        template="""
You are a senior clinical AI quality reviewer. Your job is to critically evaluate a clinical decision support summary generated by an AI assistant. You must identify any potential errors, hallucinations, missing information, guideline mismatches, or contradictions.

## PATIENT CLINICAL DATA (Ground Truth)
{patient_info}

## CURRENT VISIT
{current_visit}

## VITALS
{vitals}

## LABORATORY RESULTS (Selected)
{labs}

## EPISODIC MEMORY (Patient History)
{episodic_summary}

## ORIGINAL AI-GENERATED CASE SUMMARY
{case_summary}

## ORIGINAL AI REASONING TRACE
{reasoning}

## GUIDELINES USED
{guidelines}

## YOUR CRITIQUE TASK
Carefully review the AI-generated summary and reasoning against the actual patient data, guidelines, and episodic memory. 
Specifically check for historical inconsistencies (e.g., repeating failed treatments, suggesting medications the patient has allergies to, or ignoring previous diagnoses).

Respond ONLY in the following JSON format without markdown code blocks:
{{
  "critique_text": "Overall 3-4 sentence assessment of the quality of the AI reasoning",
  "evidence_assessment": "Strong / Moderate / Weak — with 1-2 sentence explanation",
  "missing_info_flags": [
    "Flag 1: ...",
    "Flag 2: ..."
  ],
  "hallucination_flags": [
    "Flag 1: Any claim not supported by the data (or 'None identified')",
    "Flag 2: ..."
  ],
  "contradiction_flags": [
    "Flag 1: Any internal contradictions (or 'None identified')",
    "Flag 2: ..."
  ],
  "guideline_alignment": "Well-aligned / Partially aligned / Not aligned — with explanation",
  "revised_reasoning": "If improvements are needed, provide a refined 2-3 sentence clinical reasoning. If original is good, state 'Original reasoning is adequate'",
  "critique_score": 0.75
}}
"""
    )

    # Format blocks
    patient_info = f"Allergies: {', '.join(patient.get('allergies', ['None']))}"
    
    current_visit_info = f"""
Chief Complaint: {visit.get('chief_complaint', 'Unknown')}
Symptoms: {', '.join(visit.get('symptoms', []))}
    """.strip()
    
    vitals_info = f"""
Blood Pressure: {vitals.get('blood_pressure', 'N/A')}
SpO2: {vitals.get('spo2', 'N/A')}
Temperature: {vitals.get('temperature', 'N/A')}
    """.strip()

    labs_info = f"""
HbA1c: {labs.get('Glucose', {}).get('HbA1c', 'N/A')}%
Creatinine: {labs.get('KFT', {}).get('Creatinine', 'N/A')} mg/dL
eGFR: {labs.get('KFT', {}).get('eGFR', 'N/A')} mL/min
WBC: {labs.get('CBC', {}).get('WBC', 'N/A')} x10³/μL
CRP: {labs.get('Inflammatory', {}).get('CRP', 'N/A')} mg/L
    """.strip()

    guidelines_info = chr(10).join(guidelines_used[:3]) if guidelines_used else "None provided"

    chain = LLMChain(
        llm=llm,
        prompt=prompt_template,
        verbose=True
    )

    try:
        response_text = chain.run(
            patient_info=patient_info,
            current_visit=current_visit_info,
            vitals=vitals_info,
            labs=labs_info,
            case_summary=case_summary,
            reasoning=reasoning,
            guidelines=guidelines_info,
            episodic_summary=episodic_summary
        )

        raw_text = response_text.strip()
        if "```json" in raw_text:
            raw_text = raw_text.split("```json")[1].split("```")[0].strip()
        elif "```" in raw_text:
            raw_text = raw_text.split("```")[1].split("```")[0].strip()

        parsed = json.loads(raw_text)

    except Exception as e:
        parsed = {
            "critique_text": f"Critique agent encountered an error: {str(e)}",
            "evidence_assessment": "Unable to assess",
            "missing_info_flags": ["Critique unavailable"],
            "hallucination_flags": ["None identified"],
            "contradiction_flags": ["None identified"],
            "guideline_alignment": "Unable to assess",
            "revised_reasoning": "Review original reasoning manually",
            "critique_score": 0.5,
        }

    return {
        "patient_id": patient["patient_id"],
        "visit_id": visit["visit_id"],
        "critique_text": parsed.get("critique_text", ""),
        "evidence_assessment": parsed.get("evidence_assessment", ""),
        "missing_info_flags": parsed.get("missing_info_flags", []),
        "hallucination_flags": parsed.get("hallucination_flags", []),
        "contradiction_flags": parsed.get("contradiction_flags", []),
        "guideline_alignment": parsed.get("guideline_alignment", ""),
        "revised_reasoning": parsed.get("revised_reasoning", ""),
        "critique_score": float(parsed.get("critique_score", 0.5)),
    }
